/**
 * Compile data/database-WW.xlsx → src/lib/server/ww/data.ts (a plain TS
 * module the rest of the codebase imports). Re-run whenever the xlsx
 * is updated. The output file is committed; the runtime never reads
 * the xlsx itself (Cloudflare Pages has no filesystem).
 *
 *   npx tsx scripts/ww-build-data.ts
 */
import { readFile, writeFile, mkdir } from 'fs/promises';
import { dirname } from 'path';
import * as XLSX from 'xlsx';

const SRC = './data/database-WW.xlsx';
const OUT = './src/lib/server/ww/data.ts';

// Sheets the build understands. Add new ones here when Paul populates them.
const SHEETS = [
  'Viande & Poisson',
  'Fruit & Légume',
  'Epicerie & Condiment',
  'Féculent',
  'Fromage & Produit Laitier',
  'Epicerie sucré & Goûter'
] as const;

type Entry = { name: string; points: number; quantity: string | null; sheet: string };

const buf = await readFile(SRC);
const wb = XLSX.read(buf, { type: 'buffer' });

const entries: Entry[] = [];

for (const sheet of SHEETS) {
  if (!wb.SheetNames.includes(sheet)) {
    console.warn(`⚠ sheet "${sheet}" missing — skipped`);
    continue;
  }
  const rows = XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sheet], {
    header: 1,
    defval: ''
  });

  // Skip the first 2 header rows (title + column headers). Inside, accept
  // rows where column 0 is a non-empty string and column 2 is a finite number.
  for (const row of rows.slice(2)) {
    if (!Array.isArray(row)) continue;
    const [rawName, rawQty, rawPts] = row as [unknown, unknown, unknown];
    if (typeof rawName !== 'string') continue;
    const name = rawName.trim();
    if (!name) continue;
    // Skip section dividers like "— Viandes maigres (0 pts) —"
    if (name.startsWith('—') || name.startsWith('-')) continue;
    // Skip header-like leftovers
    if (/^aliments?$/i.test(name)) continue;

    let pts: number;
    if (typeof rawPts === 'number' && Number.isFinite(rawPts)) {
      pts = rawPts;
    } else if (typeof rawPts === 'string' && rawPts.trim() !== '') {
      const n = parseFloat(rawPts.replace(',', '.'));
      if (!Number.isFinite(n)) continue;
      pts = n;
    } else {
      continue;
    }

    const qty =
      typeof rawQty === 'string' && rawQty.trim() ? rawQty.trim() : null;

    entries.push({ name, points: pts, quantity: qty, sheet });
  }
}

// De-dupe on normalized name, keeping the LOWEST points value (safer for
// the UI badge — if WW listed "Saumon 0pts" and somewhere else "Saumon
// fumé 2pts", we still want a 0pt mention to be possible). Sheet kept
// from the first occurrence.
const normalize = (s: string) =>
  s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[’']/g, "'")
    .replace(/\s+/g, ' ')
    .trim();

const byKey = new Map<string, Entry>();
for (const e of entries) {
  const key = normalize(e.name);
  const prev = byKey.get(key);
  if (!prev || e.points < prev.points) byKey.set(key, e);
}

const deduped = Array.from(byKey.values()).sort((a, b) =>
  a.name.localeCompare(b.name, 'fr')
);

const zeroCount = deduped.filter((e) => e.points === 0).length;

const header = `/**
 * GENERATED by scripts/ww-build-data.ts from data/database-WW.xlsx.
 *
 * Do NOT edit by hand — re-run \`npx tsx scripts/ww-build-data.ts\` after
 * updating the spreadsheet.
 *
 * Built ${new Date().toISOString()} — ${deduped.length} entries (${zeroCount} ZeroPoints).
 */

export type WwEntry = {
  /** Display name as written in the WW app (French). */
  name: string;
  /** SmartPoints value WW assigns to a normal portion. 0 = ZeroPoints. */
  points: number;
  /** Free-text portion size if specified ("à volonté", "100g", ...). */
  quantity: string | null;
  /** Sheet of origin in database-WW.xlsx. */
  sheet: string;
};

export const WW_ENTRIES: WwEntry[] = `;

const body = JSON.stringify(deduped, null, 2);

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, header + body + ';\n');

console.log(`✅ wrote ${OUT}`);
console.log(`   ${deduped.length} unique entries`);
console.log(`   ${zeroCount} ZeroPoints (= 0 pts)`);
const bySheet = new Map<string, number>();
for (const e of deduped) bySheet.set(e.sheet, (bySheet.get(e.sheet) ?? 0) + 1);
console.log('   by sheet:');
for (const [s, n] of bySheet) console.log(`     ${s.padEnd(30)} ${n}`);
