/**
 * GENERATED by scripts/ww-build-data.ts from data/database-WW.xlsx.
 *
 * Do NOT edit by hand — re-run `npx tsx scripts/ww-build-data.ts` after
 * updating the spreadsheet.
 *
 * Built 2026-05-25T00:46:09.763Z — 383 entries (383 ZeroPoints).
 */

export type WwEntry = {
  /** Display name as written in the WW app (French). */
  name: string;
  /** SmartPoints value WW assigns to a normal portion. 0 = ZeroPoints. */
  points: number;
  /** Free-text portion size if specified ("à volonté", "100g", ...). */
  quantity: string | null;
  /** Sheet of origin in database-WW.xlsx. */
  sheet: string;
};

export const WW_ENTRIES: WwEntry[] = [
  {
    "name": "Abricot",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Agaric champêtre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Aiguillat",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Airelles",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Alose",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Ananas",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Anchois",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Anguille",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Anone",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Araignée de porc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Artichaut",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Asperge",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Aubergine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Baies de sureau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Banane",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Banane plantain",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Bar",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Barbue",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Batavia",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Baudroie",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Bavette de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Betterave rouge",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Bigorneaux",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Blanc d'oeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Blette",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Boeuf pour tartare 5% MG",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Bolets",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Bonite",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Brochet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Brochette d’agneau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Brochette de porc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Brocoli",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Brosme",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Brugnon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Bulots",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Butternut",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Cabillaud",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Calamar",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Canneberge fraîche",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Carambole",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Carangue",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cardine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cardon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Carotte",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Carpe",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Carré d’agneau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Carré de porc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Carrelet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cassis",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Caviar",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Céleri",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Cerise",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Champignons",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Châtaignes",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chatrou",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Chayotte",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chérimole",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chicon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chicorée",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chinchard",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Chou",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chou kale",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chou pak-choi",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chou romanesco",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Chou-fleur",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Choux de Bruxelles",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Christophine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Citron",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Citron vert",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Citrouille",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Cive",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Clam",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Clémentine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Cocktail de fruits de mer",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cœur d’artichaut",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Coeur de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cœur de palmier",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Coeur de poulet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Coing",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Colin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Collier de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Compote sans sucre ajouté",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Concombre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Congre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Coquelet sans peau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Coques",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cornichon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Cornichon aigre-doux",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Cornichon au vinaigre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Côte d’agneau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cottage cheese nature 0%",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Courge spaghetti",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Courgette",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Couteaux",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Crabe",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cresson",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Crevettes",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Crosne",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Cuisse de dinde sans peau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cuisse de poulet sans peau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Cuisses de grenouille",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Dinde sans peau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Dorade",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Echalote",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Ecrevisses",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Eglefin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Émincé de porc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Empereur",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Encornet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Endive",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Entrecôte de boeuf dégraissée",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Entrecôte de cheval",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Entremets au soja nature",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Epaule de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Epaule de veau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Eperlan",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Epinard",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Escalope de porc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Escalope ou filet de dinde",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Escalope ou filet de poulet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Escalope ou noix de veau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Escargots",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Espadon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Esturgeon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Faisselle nature 0%",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Faux-filet de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Faux-filet de cheval",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Fenouil",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Feuille de chêne",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Feuille de vigne",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Fèves",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Figue de barbarie",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Figue fraîche",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Filet de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Filet de mouton",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Filet mignon de porc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Flageolets",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Flétan",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Flocons d'avoine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Flocons de quinoa",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Flocons de riz complet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Flocons de sarrasin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Foie de génisse",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Foie de lapin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Foie de lotte",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Foie de morue",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Foie de porc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Foie de poulet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Foie de veau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Foie de volaille",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Fond d’artichaut",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Fraise",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Framboise",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Fromage blanc 0% nature",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Fromage frais type yaourt nature 0% MG",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Fruit à pain",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Fruit de la passion",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Fruit du jaquier",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Fruits de mer",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Gambas",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Germe de soja",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Gésier de poulet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Gésiers",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Gigot d’agneau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Gîte à la noix de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Gombos",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Goyave",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Graines de soja crues",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Grand sébaste",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Grenade",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Grenadier",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Grondin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Groseilles",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Gruau d'avoine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haché de volaille moins de 10% MG",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Haddock",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Hampe de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Hareng",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Hareng fumé",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Haricot beurre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Haricot vert",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Haricots azuki",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haricots blancs",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haricots coco cuits",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haricots de Lima",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haricots lingots",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haricots mungo",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haricots noirs",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haricots pinto",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Haricots rouges",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Hoki",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Homard",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Huîtres",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Igname cuite",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Jambon de dinde ou blanc de dinde",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Jambon de poulet ou blanc de poulet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Jarret de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Joëls",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Julienne",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Jumeau de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Kaki",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Kiwi",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Kumquat",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Lambi",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Langouste",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Langoustine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Lentilles blondes",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Lentilles corail",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Lentilles germées",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Lentilles vertes",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Lidl Bulots cuits pasteurisés",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Lieu",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Limande",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Lingue bleue",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Litchi",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Lompe",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Lotte",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Loup",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Mâcre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Maïs doux en conserve",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Maïs en épi",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Maïs en grains",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Mandarine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Mangoustan",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Mangue",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Manioc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Manioc cuit",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Maquereau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Maquereau au naturel en conserve",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Maracuja",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Marrons",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Melon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Merlan",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Merlu",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Mérou",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Miettes de crabe",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Mini épi de maïs",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Mirabelle",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Mogettes",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Morue",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Moules",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Muge",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Mulet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Mûres",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Myrtilles",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Navet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Nectarine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Nèfle",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Noix de pétoncles",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Noix de Saint-Jacques",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Oeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Oignon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Oignon jaune",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Omble chevalier",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Onglet de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Orange",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Ormeau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Orphie commune",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Ouassou",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Oursin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Paleron de veau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Palourde",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Pamplemousse",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Panais",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Panga",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Papaye",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Pastèque",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Patate douce",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Pâtisson",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Pêche",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Perche",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Petit suisse nature 0%",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Petits pois",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Pissenlit",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Plie",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Poire",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Poireau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Pois cassés",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Pois chiches",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Féculent"
  },
  {
    "name": "Pois gourmand",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Poisson blanc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Poisson chat, pangasius",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Poitrine de veau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Poivron",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Pomélo",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Pomme",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Pomme de terre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Potimarron",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Potiron",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Poulet rôti sans peau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Poulpe",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Pousse d’épinard",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Pousse de bambou",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Praire",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Protéines de soja déshydratées",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Prune",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Quorn",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Radis",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Radis noir",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Raie",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Raisin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Raisin blanc",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Raisin noir",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Ramboutan",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Rascasse",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Requin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rhubarbe",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Ris de veau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rognons",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rosbif",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rôti de dinde dans le filet sans barde",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rôti de porc dans le filet",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rôti de veau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rouget",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Roussette",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rumsteck de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Rutabaga",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Sabre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Saint-Pierre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Salade",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Salade de fruits frais nature sans sucres ajoutés",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Salicorne",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Salsifis",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Sandre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Sardine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Saumon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Saumon fumé",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Saumonette",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Scarole",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Sébaste",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Seiche",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Selle d’agneau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Silure",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Skyr 0% nature",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Sole",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Sot-l'y-laisse de dinde",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Soupe de légumes sans MG sans féculents",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Sprat",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Steak de boeuf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Steak haché de boeuf 10% MG",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Steak haché de boeuf 5% MG",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Sucrine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Tacaud",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Tanche",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Tangerine",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Taro",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Tempeh",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Tende de tranche de cheval",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Tétragone cornue",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Thon",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Thon au naturel en conserve",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Thon rouge",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Tilapia",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Tofu",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Tofu fumé",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Tofu soyeux",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Tomate",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Tomate cerise",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Tomate côtelée",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Topinambour",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Topinambour cuit",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fruit & Légume"
  },
  {
    "name": "Tripes nature",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Truite",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Truite arc en ciel",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Truite fumée",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Truite saumonée",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Turbot",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Veau pour blanquette",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande d’autruche",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande de biche",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande de bison",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande de cerf",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande de chèvre",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande de chevreau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande de chevreuil",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande de lapin",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Viande de sanglier",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Vivaneau",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Viande & Poisson"
  },
  {
    "name": "Yaourt 0% nature",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Yaourt au lait de brebis 0% nature",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Yaourt au lait de chèvre 0% nature",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Yaourt brassé nature 0%",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  },
  {
    "name": "Yaourt Grec nature 0%",
    "points": 0,
    "quantity": "à volonté",
    "sheet": "Fromage & Produit Laitier"
  }
];
